### PR TITLE
feat: Make Project Retrospective editable

### LINKED ISSUE #685: Make project retrospectives editable
It's not cool when you can't change what you just posted.

Visual direction: let's reuse the message layout. Wider box with (...) menu to access the Edit action, boost widget, and comments below.

### PR DESCRIPTION
**Pull request by Rockyy174**
A Project Retrospective is now editable. 
Solves https://github.com/operately/operately/issues/685.

### CODE REVIEW

**Comment by shiroyasha** [comment]
I have one thing that bit me while working on project contributor editing: If the user opens the page, makes no changes, and clicks save, we should avoid creating an empty activity feed item. I would like to avoid introducing any more update actions in the API that behave like that.

One way to solve this is on the frontend: When clicking the save button we can check if there are changes, and if not, we can just redirect back.

Alternatively, we could check in on the backend, by comparing pervious/new data, and simply returning 200 without making any modifications.

**Comment by Rockyy174** [comment]
Makes sense. With the project contributors page, did you take the backend or frontend approach?

**Comment by shiroyasha** [comment]
I went with the frontend approach, but to be honest, I'm not sure that I've made the right decision. If we can, I would go with the backend one.

**Comment by Rockyy174** [comment]
What do you think about this approach, @shiroyasha?

I wasn't sure if I should handle it at the mutation or operation level. I went with the operation level because we might use the operation somewhere else in the application.

**Comment by shiroyasha** [comment]
Looks good 👍

**Pull request merged**
