### PR TITLE
feat: Show a reviewer placeholder when project has no reviewer

### PR DESCRIPTION
**Pull request by shiroyasha**
Screenshot 2024-09-06 at 23 50 20

### CODE REVIEW

**Comment by shiroyasha** [comment]
I ended up using some custom colors 🙈 We should fix this.

**Comment by shiroyasha** [comment]
related to https://github.com/operately/operately/issues/591

**Comment by markoa** [comment]
`callout-warning` colors should work

**Comment by shiroyasha** [comment]
Started with those ones. In light mode it looked good, but in dark it changed from a small nudge to a very aggressive attention grabbing color.

Screenshot 2024-09-07 at 01 07 31

Screenshot 2024-09-07 at 01 07 56

Maybe its just a sign that we need to dial down the prominence of some colors in dark mode.

**Comment by markoa** [comment]
Yeah personally find the dark version fine as it is a kind of warning
situation.

**Pull request merged**
