### PR TITLE
fix: Make discussions mobile responsive

### PR DESCRIPTION
**Pull request by markoa**
before:
Screenshot 2024-10-14 at 10 45 41

after:
Screenshot 2024-10-14 at 10 45 52

### CODE REVIEW

**Comment by shiroyasha** [comment]
@markoa as this touches every page in operately, please double check if every major page still looks good.

**Comment by shiroyasha** [comment]
Second thing: IMHO we don't need margins around the page on mobile. Snap it to the border of the screen.

**Comment by markoa** [comment]
> please double check if every major page still looks good.

Thanks for the reminder. I realized I haven't checked Goals on desktop and there was a glitch that I fixed by removing some unnecessary changes in PaperContainer.

> we don't need margins around the page on mobile. Snap it to the border of the screen.

Many changes here reduce margins on mobile, I'd postpone snapping content to another PR.

**Comment by markoa** [comment]
Linter caught a kind of a type error that I fixed, the build is green now.

**Pull request merged**
