### PR TITLE
chore: Change description for connecting projects to the goal

### PR DESCRIPTION
**Pull request by SeanAverS**
Change description in #1207 for `connecting projects to the goal`

### CODE REVIEW

**Comment by shiroyasha** [comment]
First off, thank you so much for your contribution! It's awesome to see your first PR here 🎉

There's just one small thing that needs to be added before we can merge it. There are [two more instances of the same problem](https://github.com/operately/operately/pull/1230/files#diff-edc43f7c459c8a272eed37f8d188d9d2200e3b90bcbdb19554dffcd1ae4c98c8R35-R42) in the file. Once that's done, we’ll be all set to move forward!

Thanks again for your efforts, and feel free to ask if you need any help or clarification.

**Comment by shiroyasha** [comment]
Thanks for fixing it!

One last thing is: It looks like your pull request is missing the required "Signed-off-by" line in your commits. This is needed to confirm that you agree that your work will be licensed as open-source with the same license as the project (Apache 2.0).

To fix this, you'll need to add the sign-off to both of your commits. You can do this by running the following commands:

```
git rebase --signoff HEAD~2
git push --force-with-lease
```

Let me know if you need any assistance with this.

**Comment by shiroyasha** [comment]
Everything looks great @SeanAverS! Congrats on your first merged pull-request in Operately.

**Comment by SeanAverS** [comment]
thank you @shiroyasha for your paitience and helpful instructions ::thumbsup::

**Pull request merged**
